### ISSUE TITLE
A dotfile for pfp-vim

### ISSUE THREAD

**Issue by Fuzion24** [d0c-s4vage/pfp-vim#3]
It would be nice to not have specify the directory where the templates exist every time and to only choose from a list that exist

**Comment by d0c-s4vage** [comment]
There is!

https://github.com/d0c-s4vage/pfp-vim/blob/master/plugin/pfp.vim#L151-L163

Use the `PfpInit` command (one time) to set the directory, or use it multiple times to add multiple directories. Those paths should be stored in `~/.pfp` and will be used every time you run the `PfpParse` command.
